name: Test oidc provider

on:
  workflow_dispatch:

jobs:
  list-s3-bucket:
  runs-on: ubuntu-latest
  defaults:
    run:
      shell: bash
  permissions:
    id-token: write
    contents: read
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-southeast-2

    - name: List S3 bucket
      run: |
        aws s3 ls
